[pytest]
# Минимальная версия pytest
minversion = 7.0

# Директории с тестами
testpaths = tests

# Паттерны для поиска тестов
python_files = test_*.py
python_classes = Test*
python_functions = test_*

asyncio_mode = auto

pythonpath = src

# Опции по умолчанию
addopts =
    -v
    --strict-markers
    --tb=short
    --disable-warnings
    -p no:warnings

# Маркеры
markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    slow: Slow tests
    asyncio: Async tests
