"""delete attempt from login code

Revision ID: 452edfca4bc4
Revises: 0f79ae7fced0
Create Date: 2026-06-11 15:18:20.532537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452edfca4bc4'
down_revision: Union[str, Sequence[str], None] = '0f79ae7fced0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_code', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_code', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
