"""create user admin

Revision ID: ed794e84152a
Revises: 452edfca4bc4
Create Date: 2026-07-01 19:51:09.646134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed794e84152a'
down_revision: Union[str, Sequence[str], None] = '452edfca4bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_admin_email'), 'user_admin', ['email'], unique=True)
    op.create_index(op.f('ix_user_admin_id'), 'user_admin', ['id'], unique=False)
    op.create_index(op.f('ix_user_admin_username'), 'user_admin', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin_username'), table_name='user_admin')
    op.drop_index(op.f('ix_user_admin_id'), table_name='user_admin')
    op.drop_index(op.f('ix_user_admin_email'), table_name='user_admin')
    op.drop_table('user_admin')
    # ### end Alembic commands ###
